/* ============================================================
   Build the Gallery page data (js/data/gallery.js)
   Collects the gallery arrays from js/data/events/*.js plus every
   photo in assets/images/felicitations/, measures each image, and
   writes window.GALLERY_DATA for js/gallery.js.

   - Each photo records its real pixel size (w, h) so the collage can
     lay out its rows before any image has loaded.
   - `thumb` points at the preview in assets/images/thumbs/ (run
     build:thumbs first); photos without one fall back to `src`.
   - Collections are spread evenly through the "All" view so
     neighbouring tiles come from different events.
   - Film stills (js/data/projects/) are not part of the gallery.

   Run from the repo root:  npm run build:gallery
   ============================================================ */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');
const sharp = require('sharp');

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = 'js/data/gallery.js';
const FELICITATIONS = 'assets/images/felicitations';

/* Photos that stay on their event page but are left out of the gallery. */
const EXCLUDE = new Set([
  'assets/images/events/bangaru-bidda-stage-play/photo-02.jpg',
  'assets/images/events/bangaru-bidda-stage-play/photo-09.jpg',
  'assets/images/events/enjoy-every-moment-premiere-event/photo-02.jpg',
  'assets/images/events/sangaseva-puraskaram/photo-03.jpg',
  'assets/images/events/sangaseva-puraskaram/photo-11.jpg',
  'assets/images/events/sangaseva-puraskaram/photo-12.jpg',
]);

function loadData(file) {
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(file, 'utf8'), sandbox, { filename: file });
  return Object.values(sandbox.window)[0];
}

/* [{ kind, title, href, items: [{ src, alt }] }] in display-priority order. */
function collections() {
  const out = [];
  const dir = 'js/data/events';
  for (const name of fs.readdirSync(path.join(ROOT, dir)).filter(n => n.endsWith('.js')).sort()) {
    const slug = name.replace(/\.js$/, '');
    const data = loadData(path.join(ROOT, dir, name));
    const items = (data.gallery || [])
      .filter(g => g.image && !g.placeholder)
      .map(g => ({ src: g.image.replace(/^\.\.\//, ''), alt: g.alt || '' }));
    out.push({
      kind: 'events',
      title: (data.hero && (data.hero.name || data.hero.title)) || slug,
      href: 'events/' + slug + '.html',
      items,
    });
  }
  const felicitations = fs.readdirSync(path.join(ROOT, FELICITATIONS))
    .filter(n => /\.jpe?g$/i.test(n)).sort()
    .map((n, i) => ({ src: FELICITATIONS + '/' + n, alt: 'Felicitation moment ' + (i + 1) }));
  out.push({ kind: 'felicitations', title: 'Felicitations', href: '', items: felicitations });
  return out;
}

async function main() {
  const seen = new Set(EXCLUDE);
  const sets = [];
  for (const c of collections()) {
    const items = [];
    for (const it of c.items) {
      if (seen.has(it.src)) continue;               // excluded, or already listed by an earlier event
      seen.add(it.src);
      const file = path.join(ROOT, it.src);
      if (!fs.existsSync(file)) throw new Error('Missing image referenced by a data file: ' + it.src);
      const { width, height } = await sharp(file).metadata();
      const photo = { src: it.src, w: width, h: height, alt: it.alt };
      const thumb = it.src.replace('assets/images/', 'assets/images/thumbs/');
      if (fs.existsSync(path.join(ROOT, thumb))) photo.thumb = thumb;
      items.push(photo);
    }
    if (items.length) sets.push({ ...c, items });
  }

  // Spread each collection evenly across the collage: order every photo by
  // its relative position within its own set, ties broken by set order.
  const photos = sets
    .flatMap((c, ci) => c.items.map((it, i) => ({
      key: (i + 0.5) / c.items.length,
      ci,
      photo: Object.assign({ kind: c.kind, title: c.title }, c.href ? { href: c.href } : {}, it),
    })))
    .sort((a, b) => a.key - b.key || a.ci - b.ci)
    .map(x => x.photo);

  const body =
    '/* Gallery page data — generated by tools/build-gallery.js (npm run build:gallery)\n' +
    '   from the gallery arrays in js/data/events/*.js plus every photo in\n' +
    '   assets/images/felicitations/. Do not edit by hand. Each photo carries its\n' +
    '   real pixel size (w, h) so the collage can lay out rows before any\n' +
    '   image has loaded. `thumb` is a smaller preview copy used by the\n' +
    '   collage; the lightbox opens the full-size `src`. */\n' +
    'window.GALLERY_DATA = ' + JSON.stringify(photos, null, 2) + ';\n';
  fs.writeFileSync(path.join(ROOT, OUTPUT), body);

  console.log(`${photos.length} photos from ${sets.length} collections -> ${OUTPUT}`);
  sets.forEach(c => console.log(`  ${c.kind.padEnd(13)} ${c.title} (${c.items.length})`));
  const missing = photos.filter(p => !p.thumb).length;
  if (missing) console.log(`  ${missing} photo(s) have no preview yet; run npm run build:thumbs`);
}

main().catch(err => { console.error(err.message); process.exit(1); });
